# Generated by Django 4.2.6 on 2023-11-13 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a title to identify this item", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe in detail the item", null=True, verbose_name="description"
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("date_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Received"), (1, "Analysis"), (2, "To Quote"), (-1, "Rejected"), (-2, "Returned")],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="the item belongs to this customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        help_text="user currently working on or responsible for this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a title to identify this item", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe in detail the item", null=True, verbose_name="description"
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("date_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Sent"),
                            (2, "Approved"),
                            (-1, "Rejected"),
                            (3, "Closed"),
                            (-2, "Cancelled"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Price proposed"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("AED", "UAE Dirham"), ("USD", "US Dollar"), ("EUR", "Euro"), ("GBP", "UK Pound")],
                        default="AED",
                        max_length=3,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True, help_text="Terms and Conditions for this Quotation", null=True, verbose_name="Terms"
                    ),
                ),
                (
                    "validity",
                    models.DateField(
                        blank=True, help_text="date until this quotation is valid", null=True, verbose_name="Validity"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="the item belongs to this customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        help_text="user currently working on or responsible for this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobcycle.requirement",
                        verbose_name="Requirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation",
                "verbose_name_plural": "Quotations",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a title to identify this item", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe in detail the item", null=True, verbose_name="description"
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("date_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Not Started"),
                            (2, "In Progress"),
                            (3, "In Review"),
                            (4, "Delivered"),
                            (5, "Rework"),
                            (-1, "Closed"),
                            (-2, "Cancelled"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "invoiced",
                    models.SmallIntegerField(
                        choices=[(0, "Not invoiced"), (1, "Partially Invoiced"), (2, "Fully Invoiced")],
                        default=0,
                        verbose_name="invoiced",
                    ),
                ),
                (
                    "paid",
                    models.SmallIntegerField(
                        choices=[(0, "Not paid"), (1, "Partially paid"), (2, "Fully paid")],
                        default=0,
                        verbose_name="paid",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Price accepted"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("AED", "UAE Dirham"), ("USD", "US Dollar"), ("EUR", "Euro")],
                        default="AED",
                        max_length=3,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True, help_text="Terms and Conditions for this Job", null=True, verbose_name="Terms"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="the item belongs to this customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        help_text="user currently working on or responsible for this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobcycle.quotation",
                        verbose_name="Quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
    ]
