# Generated by Django 4.2.6 on 2023-11-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("jobcycle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="customer",
            field=models.ForeignKey(
                help_text="the item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="deadline"),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                help_text="the item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="deadline"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="customer",
            field=models.ForeignKey(
                help_text="the item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="Delivery date requested. This is only informational and there is no commitment until the Quotation is sent and approved",
                null=True,
                verbose_name="deadline",
            ),
        ),
    ]
