# Generated by Django 4.2.6 on 2023-11-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobcycle", "0003_alter_job_owner_alter_quotation_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("AED", "UAE Dirham"), ("USD", "US Dollar"), ("EUR", "Euro"), ("GBP", "UK Pound")],
                default="AED",
                max_length=3,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Sent"),
                    (2, "Approved"),
                    (-1, "Rejected"),
                    (3, "Negotiate"),
                    (-2, "Cancelled"),
                ],
                default=0,
                verbose_name="status",
            ),
        ),
    ]
