# Generated by Django 4.2.6 on 2023-11-15 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobcycle", "0004_alter_job_currency_alter_quotation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a title to identify this item", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe in detail the item", null=True, verbose_name="description"
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True, verbose_name="deadline")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("date_closed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Draft"),
                            (1, "Sent"),
                            (2, "Partial"),
                            (3, "Paid"),
                            (4, "Overdue"),
                            (-2, "Cancelled"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Total Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("AED", "UAE Dirham"), ("USD", "US Dollar"), ("EUR", "Euro"), ("GBP", "UK Pound")],
                        default="AED",
                        max_length=3,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, choices=[("VAT", "VAT")], max_length=5, null=True, verbose_name="Tax Code"
                    ),
                ),
                (
                    "tax_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax Percentage to be added to the price",
                        max_digits=6,
                        null=True,
                        verbose_name="Tax %",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="the item belongs to this customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this job will be used for all the line items for this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobcycle.job",
                        verbose_name="Job",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="user currently working on or responsible for this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a title to identify this line item", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="If needed, provide additional detail for this line item",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Quantity of this line item",
                        max_digits=6,
                        verbose_name="quantity",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="price")),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, choices=[("VAT", "VAT")], max_length=5, null=True, verbose_name="Tax Code"
                    ),
                ),
                (
                    "tax_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax Percentage to be added to the price",
                        max_digits=6,
                        verbose_name="Tax %",
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="paid")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineitems",
                        to="jobcycle.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this job will be used for all the line items for this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobcycle.job",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
            },
        ),
    ]
