# Generated by Django 4.2.6 on 2023-12-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("jobcycle", "0005_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                help_text="The item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="customer",
            field=models.ForeignKey(
                help_text="The item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                help_text="The item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="customer",
            field=models.ForeignKey(
                help_text="The item belongs to this customer",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
    ]
