# Generated by Django 4.2.6 on 2023-11-12 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                (
                    "tax_id_number",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Tax Identification Nr"),
                ),
                (
                    "billing_address",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Billing Address"),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Stripe ID"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
