# Generated by Django 4.2.6 on 2023-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0002_attachment_fileattachment_delete_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="flow",
            field=models.CharField(
                blank=True,
                choices=[("I", "Input"), ("W", "Work"), ("O", "Output"), ("D", "Deliverable")],
                max_length=1,
                null=True,
                verbose_name="flow",
            ),
        ),
    ]
