# Generated by Django 4.2.6 on 2023-12-04 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attachments", "0004_alter_fileattachment_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="files_uploaded",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
    ]
